const translateColumns = {
  id: 'Идентификатор',
  title: 'Название',
  email: 'Почта',
  avatar: 'Фото профиля',
  lastName: 'Фамилия',
  subTitle: 'Подзаголовок',
  isDiscount: 'Только со скидкой',
  buttonText: 'Текст в кнопке',
  discountId: 'Скидка',
  middleName: 'Отчество',
  firstName: 'Фамилия',
  value: 'Значение',
  dateOfBirth: 'Дата рождения',
  lowNotes: 'Нижние ноты',
  abbreviation: 'Аббревиатура',
  topNotes: 'Верхние ноты',
  sentiment: 'Ощущения',
  middleNotes: 'Средние ноты',
  images: 'Изображения',
  image: 'Изображение',
  positionId: 'Должность',
  description: 'Описание',
  price: 'Стоимость, руб',
  createdAt: 'Дата создания',
  updatedAt: 'Дата обновления',
  colorId: 'Цвет коллекции',
  typeId: 'Тип аромата',
  volumeId: 'Объем',
  genderId: 'Для кого',
  motiveId: 'Мотив',
  employeeId: 'Сотрудник',
  resource: 'Ресурс',
  action: 'Действие',
  recordId: 'Идентификатор объекта',
  recordTitle: 'Название объекта',
  deliveryId: 'Вид доставки',
  paymentId: 'Вид оплаты',
  recipientId: 'Получатель',
  orderId: 'Заказ',
  statusId: 'Статус заказа',
  userId: 'Пользователь',
  totalPrice: 'Стоимость заказа, руб',
  totalPriceDiscount: 'Скидка, руб',
  totalPriceWithDiscount: 'Стоимость со скидкой, руб',
  difference: 'Изменения',
  products: 'Товары в заказе',
};

export const translateResources = (resources) => {
  return resources.reduce(
    (acc, { options }) => ({
      ...acc,
      [options.id]: {
        properties: translateColumns,
        actions: {
          new: 'Создать',
          edit: 'Редактировать',
          delete: 'Удалить',
          filter: 'Фильтровать',
          show: 'Подробнее',
          bulkDelete: 'Удалить выбранные',
          list: 'Все',
          search: 'Поиск',
        },
      },
    }),
    {},
  );
};
